[package]
name = "tm"
version = "0.3.6"
authors = ["Paul Jickling <pjickling@gmail.com>"]
edition = "2018"
description = "A time manager tool that tracks time spent on specified activities"
license = "MIT"
repository = "https://github.com/pauljickling/time-manager"

[dependencies]
dirs = "1.0.5"
